{
  "Severity": "HIGH",
  "UpdatedAt": "2023-08-11T05:02:59Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "tlslite"
  },
  "Advisory": {
    "DatabaseId": 92111,
    "Id": "GSA_kwCzR0hTQS00NzQ5LXA3cngtOGpqas4AAWfP",
    "GhsaId": "GHSA-4749-p7rx-8jjj",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2015-3220"
      },
      {
        "Url": "https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853"
      },
      {
        "Url": "https://bugzilla.redhat.com/show_bug.cgi?id=1254215"
      },
      {
        "Url": "https://groups.google.com/forum/#!topic/tlslite-dev/MoWE7B0A4iU"
      },
      {
        "Url": "https://github.com/advisories/GHSA-4749-p7rx-8jjj"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-4749-p7rx-8jjj"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2015-3220"
      }
    ],
    "Description": "The tlslite library before 0.4.9 for Python allows remote attackers to trigger a denial of service (runtime exception and process crash).",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2022-05-14T03:07:28Z",
    "Severity": "HIGH",
    "Summary": "tlslite remote denial of service vulnerability",
    "UpdatedAt": "2023-08-11T05:02:59Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 7.5,
      "VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "0.4.9"
      },
      "VulnerableVersionRange": "\u003c 0.4.9"
    }
  ]
}