{
  "Identifier": "CVE-2023-25658",
  "PackageSlug": "pypi/tensorflow",
  "Title": "Out-of-bounds Read",
  "Description": "TensorFlow is an open source platform for machine learning. Prior to versions 2.12.0 and 2.11.1, an out-of-bounds read is in GRUBlockCellGrad. A fix is included in TensorFlow 2.12.0 and 2.11.1.",
  "Date": "2023-11-09",
  "Pubdate": "2023-03-25",
  "AffectedRange": "\u003c2.11.1",
  "FixedVersions": [
    "2.11.1"
  ],
  "AffectedVersions": "All versions before 2.11.1",
  "NotImpacted": "All versions starting from 2.11.1",
  "Solution": "Upgrade to version 2.11.1 or above.",
  "Urls": [
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-68v3-g9cm-rmm6",
    "https://github.com/tensorflow/tensorflow/commit/ff459137c2716a2a60f7d441b855fcb466d778cb",
    "https://github.com/advisories/GHSA-68v3-g9cm-rmm6"
  ],
  "CvssV2": "",
  "CvssV3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "UUID": "057a5000-c3fa-47c1-a7f9-c7c6881d514b"
}