{
  "id": "MAL-2024-9953",
  "modified": "2024-12-09T14:39:22Z",
  "published": "2024-10-16T14:37:13Z",
  "summary": "Malicious code in bughunter9 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "bughunter9",
        "purl": "pkg:pypi/bughunter9"
      },
      "versions": [
        "9.5",
        "9.6",
        "9.7",
        "9.8",
        "9.9",
        "9.10",
        "9.11",
        "9.13",
        "9.14",
        "9.15",
        "9.16",
        "9.17",
        "9.18",
        "9.19",
        "9.21",
        "9.22",
        "9.23",
        "9.20",
        "9.24",
        "9.25"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/bughunter9/MAL-2024-9953.json"
      }
    }
  ]
}