{
  "Title": "Security update for python-Django",
  "Tracking": {
    "ID": "SUSE-SU-2024:2816-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-08-07T13:32:24Z",
    "CurrentReleaseDate": "2024-08-07T13:32:24Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-08-07T13:32:24Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-Django",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-Django fixes the following issues:\n\n- CVE-2024-42005: Fixed SQL injection in QuerySet.values() and values_list() (bsc#1228629)\n- CVE-2024-41989: Fixed Memory exhaustion in django.utils.numberformat.floatformat() (bsc#1228630)\n- CVE-2024-41990: Fixed denial-of-service vulnerability in django.utils.html.urlize() (bsc#1228631)\n- CVE-2024-41991: Fixed another denial-of-service vulnerability in django.utils.html.urlize() (bsc#1228632)\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "SUSE-2024-2816,SUSE-SLE-Module-Packagehub-Subpackages-15-SP6-2024-2816,openSUSE-SLE-15.6-2024-2816",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python311-Django-4.2.11-150600.3.6.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-Django-4.2.11-150600.3.6.1",
        "RelatesToProductReference": "openSUSE Leap 15.6",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/update/announcement/2024/suse-su-20242816-1/",
      "Description": "Link for SUSE-SU-2024:2816-1"
    },
    {
      "URL": "https://lists.suse.com/pipermail/sle-security-updates/2024-August/019140.html",
      "Description": "E-Mail link for SUSE-SU-2024:2816-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1228629",
      "Description": "SUSE Bug 1228629"
    },
    {
      "URL": "https://bugzilla.suse.com/1228630",
      "Description": "SUSE Bug 1228630"
    },
    {
      "URL": "https://bugzilla.suse.com/1228631",
      "Description": "SUSE Bug 1228631"
    },
    {
      "URL": "https://bugzilla.suse.com/1228632",
      "Description": "SUSE Bug 1228632"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-41989/",
      "Description": "SUSE CVE CVE-2024-41989 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-41990/",
      "Description": "SUSE CVE CVE-2024-41990 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-41991/",
      "Description": "SUSE CVE CVE-2024-41991 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-42005/",
      "Description": "SUSE CVE CVE-2024-42005 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2024-41989",
      "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The floatformat template filter is subject to significant memory consumption when given a string representation of a number in scientific notation with a large exponent.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-41989.html",
          "Description": "CVE-2024-41989"
        },
        {
          "URL": "https://bugzilla.suse.com/1228629",
          "Description": "SUSE Bug 1228629"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.6.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.6.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-41990",
      "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-41990.html",
          "Description": "CVE-2024-41990"
        },
        {
          "URL": "https://bugzilla.suse.com/1228630",
          "Description": "SUSE Bug 1228630"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.6.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.6.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-41991",
      "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize and urlizetrunc template filters, and the AdminURLFieldWidget widget, are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-41991.html",
          "Description": "CVE-2024-41991"
        },
        {
          "URL": "https://bugzilla.suse.com/1228631",
          "Description": "SUSE Bug 1228631"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.6.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.6.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-42005",
      "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. QuerySet.values() and values_list() methods on models with a JSONField are subject to SQL injection in column aliases via a crafted JSON object key as a passed *arg.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-42005.html",
          "Description": "CVE-2024-42005"
        },
        {
          "URL": "https://bugzilla.suse.com/1228632",
          "Description": "SUSE Bug 1228632"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.6.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.6.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}