{
  "Title": "Security update for python-pymongo",
  "Tracking": {
    "ID": "SUSE-SU-2024:1571-2",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-06-13T14:33:38Z",
    "CurrentReleaseDate": "2024-06-13T14:33:38Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-06-13T14:33:38Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-pymongo",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-pymongo fixes the following issues:\n\n- CVE-2024-21506: Fixed out-of-bounds read in the BSON module (bsc#1222492)\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "SUSE-2024-1571,SUSE-SLE-Module-Packagehub-Subpackages-15-SP6-2024-1571,openSUSE-SLE-15.6-2024-1571",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python3-pymongo-3.11.0-150300.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python3-pymongo-3.11.0-150300.3.3.1",
        "RelatesToProductReference": "openSUSE Leap 15.6",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/update/announcement/2024/suse-su-20241571-2/",
      "Description": "Link for SUSE-SU-2024:1571-2"
    },
    {
      "URL": "https://lists.suse.com/pipermail/sle-updates/2024-June/035585.html",
      "Description": "E-Mail link for SUSE-SU-2024:1571-2"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1222492",
      "Description": "SUSE Bug 1222492"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-21506/",
      "Description": "SUSE CVE CVE-2024-21506 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2024-21506",
      "Description": "** REJECT ** Duplicate of CVE-2024-5629.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "moderate"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-21506.html",
          "Description": "CVE-2024-21506"
        },
        {
          "URL": "https://bugzilla.suse.com/1222492",
          "Description": "SUSE Bug 1222492"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python3-pymongo-3.11.0-150300.3.3.1",
            "openSUSE Leap 15.6:python3-pymongo-3.11.0-150300.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}