{
  "id": "PYSEC-2013-16",
  "modified": "2023-11-08T03:57:13.419369Z",
  "published": "2013-05-02T14:55:00Z",
  "aliases": [
    "CVE-2013-0305",
    "GHSA-r7w6-p47g-vj53"
  ],
  "details": "The administrative interface for Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 does not check permissions for the history view, which allows remote authenticated administrators to obtain sensitive object history information.",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django",
        "purl": "pkg:pypi/django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "1.3"
            },
            {
              "fixed": "1.3.6"
            },
            {
              "introduced": "1.4"
            },
            {
              "fixed": "1.4.4"
            }
          ]
        }
      ],
      "versions": [
        "1.3",
        "1.3.1",
        "1.3.2",
        "1.3.3",
        "1.3.4",
        "1.3.5",
        "1.4",
        "1.4.1",
        "1.4.2",
        "1.4.3"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2013-16.yaml"
      }
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://www.djangoproject.com/weblog/2013/feb/19/security/"
    },
    {
      "type": "ADVISORY",
      "url": "http://www.debian.org/security/2013/dsa-2634"
    },
    {
      "type": "WEB",
      "url": "http://ubuntu.com/usn/usn-1757-1"
    },
    {
      "type": "ADVISORY",
      "url": "http://rhn.redhat.com/errata/RHSA-2013-0670.html"
    }
  ]
}