{
  "id": "MAL-2024-10136",
  "modified": "2024-10-16T14:49:23Z",
  "published": "2024-10-16T14:49:23Z",
  "summary": "Malicious code in pytiom (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pytiom",
        "purl": "pkg:pypi/pytiom"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pytiom/MAL-2024-10136.json"
      }
    }
  ]
}