{
  "Severity": "HIGH",
  "UpdatedAt": "2024-06-12T17:13:08Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "oauthenticator"
  },
  "Advisory": {
    "DatabaseId": 249765,
    "Id": "GSA_kwCzR0hTQS1ncHJqLTNwNzUtZjk5Ns4AA8-l",
    "GhsaId": "GHSA-gprj-3p75-f996",
    "References": [
      {
        "Url": "https://github.com/jupyterhub/oauthenticator/security/advisories/GHSA-gprj-3p75-f996"
      },
      {
        "Url": "https://github.com/jupyterhub/oauthenticator/commit/d1aea05fa89f2beae15ab0fa0b0d071030f79654"
      },
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37300"
      },
      {
        "Url": "https://jupyterhub.readthedocs.io/en/stable/howto/upgrading-v5.html#authenticator-allow-all-and-allow-existing-users"
      },
      {
        "Url": "https://github.com/advisories/GHSA-gprj-3p75-f996"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-gprj-3p75-f996"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2024-37300"
      }
    ],
    "Description": "### Impact\n\nJupyterHub \u003c 5.0, when used with `GlobusOAuthenticator`, could be configured to allow all users from a particular institution only. The configuration for this would look like:\n\n```python\n# Require users to be using the \"foo.horse\" identity provider, often an institution or university\nc.GlobusAuthenticator.identity_provider = \"foo.horse\"\n# Allow everyone who has that identity provider to log in\nc.GlobusAuthenticator.allow_all = True\n```\n\nThis worked fine prior to JupyterHub 5.0, because `allow_all` *did not* take precedence over `identity_provider`.\n\nSince JupyterHub 5.0, `allow_all` *does* take precedence over `identity_provider`. On a hub with the same config, now **all** users will be allowed to login, regardless of `identity_provider`. `identity_provider` will basically be ignored.\n\nThis is a [documented change](https://jupyterhub.readthedocs.io/en/stable/howto/upgrading-v5.html#authenticator-allow-all-and-allow-existing-users) in JupyterHub 5.0,\nbut is likely to catch many users by surprise.\n\n### Patches\n\nOAuthenticator 16.3.1 fixes the issue with JupyterHub 5.0, and does not affect previous versions.\n\n### Workarounds\n\nDo not upgrade to JupyterHub 5.0 when using `GlobusOAuthenticator` in the prior configuration.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2024-06-12T17:13:07Z",
    "Severity": "HIGH",
    "Summary": "Globus `identity_provider` restriction ignored when used with `allow_all` in JupyterHub 5.0",
    "UpdatedAt": "2024-06-12T19:24:06Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 8.1,
      "VectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "16.3.1"
      },
      "VulnerableVersionRange": "\u003c 16.3.1"
    }
  ]
}