{
  "Identifier": "CVE-2008-7264",
  "PackageSlug": "pypi/pyftpdlib",
  "Title": "Improper input validation in pyftpdlib",
  "Description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
  "Date": "2024-10-23",
  "Pubdate": "2022-05-17",
  "AffectedRange": "\u003c0.5.0",
  "FixedVersions": [
    "0.5.0"
  ],
  "AffectedVersions": "All versions before 0.5.0",
  "NotImpacted": "All versions starting from 0.5.0",
  "Solution": "Upgrade to version 0.5.0 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2008-7264",
    "https://github.com/advisories/GHSA-8p2c-fghc-9hj4",
    "https://github.com/giampaolo/pyftpdlib/issues/71",
    "https://github.com/giampaolo/pyftpdlib",
    "https://github.com/pypa/advisory-database/tree/main/vulns/pyftpdlib/PYSEC-2010-6.yaml"
  ],
  "CvssV2": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
  "CvssV3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
  "UUID": "54c8717b-a470-48e9-bca8-a4b393dbf0bb"
}