{
  "Identifier": "CVE-2016-10127",
  "PackageSlug": "pypi/pysaml2",
  "Title": "PySAML2 XML external entity attack",
  "Description": "PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response.",
  "Date": "2024-10-24",
  "Pubdate": "2022-05-17",
  "AffectedRange": "\u003c4.5.0",
  "FixedVersions": [
    "4.5.0"
  ],
  "AffectedVersions": "All versions before 4.5.0",
  "NotImpacted": "All versions starting from 4.5.0",
  "Solution": "Upgrade to version 4.5.0 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2016-10127",
    "https://github.com/advisories/GHSA-m269-wj6g-c459",
    "https://github.com/rohe/pysaml2/issues/366",
    "https://github.com/rohe/pysaml2/pull/379",
    "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b",
    "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716",
    "https://github.com/pypa/advisory-database/tree/main/vulns/pysaml2/PYSEC-2017-67.yaml",
    "https://github.com/rohe/pysaml2",
    "https://web.archive.org/web/20200227195127/http://www.securityfocus.com/bid/95376"
  ],
  "CvssV2": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
  "CvssV3": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
  "UUID": "b8fd39e2-41f7-4c6a-b19d-9b6f36b38c6b"
}