{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:pgbouncer_project:pgbouncer:1.5.2:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              }
            ],
            "operator": "OR"
          },
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:postgresql:postgresql:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": false
              }
            ],
            "operator": "OR"
          }
        ],
        "cpe_match": [],
        "operator": "AND"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2012-4575"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The add_database function in objects.c in the pgbouncer pooler 1.5.2 for PostgreSQL allows remote attackers to cause a denial of service (daemon outage) via a long database name in a request."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-119"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "[oss-security] 20121102 Re: CVE Request -- pgbouncer: DoS (pooler server shutdown) by adding database with large name",
          "refsource": "MLIST",
          "tags": [
            "Mailing List",
            "Third Party Advisory"
          ],
          "url": "http://openwall.com/lists/oss-security/2012/11/02/8"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=872527",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=872527"
        },
        {
          "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692103",
          "refsource": "CONFIRM",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692103"
        },
        {
          "name": "56371",
          "refsource": "BID",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "http://www.securityfocus.com/bid/56371"
        },
        {
          "name": "http://git.postgresql.org/gitweb/?p=pgbouncer.git%3Ba=commit%3Bh=4b92112b820830b30cd7bc91bef3dd8f35305525",
          "refsource": "MISC",
          "tags": [],
          "url": "http://git.postgresql.org/gitweb/?p=pgbouncer.git%3Ba=commit%3Bh=4b92112b820830b30cd7bc91bef3dd8f35305525"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5,
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2023-02-13T04:34Z",
  "publishedDate": "2012-11-18T19:55Z"
}