{
  "Identifier": "CVE-2016-1241",
  "PackageSlug": "pypi/trytond",
  "Title": "Tryton allows users to read the hashed password",
  "Description": "Tryton 3.x before 3.2.17, 3.4.x before 3.4.14, 3.6.x before 3.6.12, 3.8.x before 3.8.8, and 4.x before 4.0.4 allow remote authenticated users to discover user password hashes via unspecified vectors.",
  "Date": "2024-11-22",
  "Pubdate": "2022-05-17",
  "AffectedRange": "\u003e=3.0.0,\u003c3.2.17||\u003e=3.4.0,\u003c3.4.14||\u003e=3.8.0,\u003c3.8.8||\u003e=3.6.0,\u003c3.6.12||\u003e=4.0.0,\u003c4.0.4",
  "FixedVersions": [
    "3.2.17",
    "3.4.14",
    "3.8.8",
    "3.6.12",
    "4.0.4"
  ],
  "AffectedVersions": "All versions starting from 3.0.0 before 3.2.17, all versions starting from 3.4.0 before 3.4.14, all versions starting from 3.6.0 before 3.6.12, all versions starting from 3.8.0 before 3.8.8, all versions starting from 4.0.0 before 4.0.4",
  "NotImpacted": "All versions before 3.0.0, all versions starting from 3.2.17 before 3.4.0, all versions starting from 3.4.14 before 3.6.0, all versions starting from 3.6.12 before 3.8.0, all versions starting from 3.8.8 before 4.0.0, all versions starting from 4.0.4",
  "Solution": "Upgrade to versions 3.2.17, 3.4.14, 3.6.12, 3.8.8, 4.0.4 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2016-1241",
    "https://github.com/advisories/GHSA-52j9-v3jc-9xgc",
    "https://github.com/tryton/trytond/commit/11424d57b7838381745655e2e89470ff9087cd27",
    "https://github.com/tryton/trytond/commit/30d2a6dcaf09340829cd70ee8a15a4941ca7161a",
    "https://bugs.tryton.org/issue5795",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tryton/PYSEC-2016-40.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/trytond/PYSEC-2016-12.yaml",
    "https://github.com/tryton/trytond"
  ],
  "CvssV2": "AV:N/AC:M/Au:S/C:P/I:N/A:N",
  "CvssV3": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
  "UUID": "7677bde1-eb8c-465f-a742-875b753496e5"
}