{
  "Identifier": "CVE-2022-23580",
  "PackageSlug": "pypi/tensorflow-cpu",
  "Title": "Uncontrolled Resource Consumption",
  "Description": "Tensorflow is an Open Source Machine Learning Framework. During shape inference, TensorFlow can allocate a large vector based on a value from a tensor controlled by the user. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.",
  "Date": "2022-02-11",
  "Pubdate": "2022-02-07",
  "AffectedRange": "\u003c2.5.3||\u003e=2.6.0,\u003c2.6.3||==2.7.0",
  "FixedVersions": [
    "2.5.3",
    "2.6.3",
    "2.7.1"
  ],
  "AffectedVersions": "All versions before 2.5.3, all versions starting from 2.6.0 before 2.6.3, version 2.7.0",
  "NotImpacted": "All versions starting from 2.5.3 before 2.6.0, all versions starting from 2.6.3 before 2.7.0, all versions after 2.7.0",
  "Solution": "Upgrade to versions 2.5.3, 2.6.3, 2.7.1 or above.",
  "Urls": [
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-627q-g293-49q7",
    "https://github.com/tensorflow/tensorflow/commit/1361fb7e29449629e1df94d44e0427ebec8c83c7",
    "https://github.com/tensorflow/tensorflow/blob/a1320ec1eac186da1d03f033109191f715b2b130/tensorflow/core/framework/shape_inference.cc#L788-L790",
    "https://nvd.nist.gov/vuln/detail/CVE-2022-23580",
    "https://github.com/advisories/GHSA-627q-g293-49q7"
  ],
  "CvssV2": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
  "CvssV3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
  "UUID": "33793b64-8559-4fa4-adf6-40faabe727c6"
}