{
  "id": "MAL-2024-4807",
  "modified": "2024-10-24T01:01:57Z",
  "published": "2024-06-25T13:32:44Z",
  "aliases": [
    "SNYK-PYTHON-BIPUTILDS-6513346"
  ],
  "summary": "Malicious code in bip-utilds (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "bip-utilds",
        "purl": "pkg:pypi/bip-utilds"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/bip-utilds/MAL-2024-4807.json"
      }
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIPUTILDS-6513346"
    }
  ]
}